backend:
  name: git-gateway
  repo: dvsrshohan/gatsby
  branch: main
  
media_folder: static/img
public_folder: /img

collections:
  - name: jobs
    label: Jobs
    folder: src/jobs
    create: true
    fields:
      - { name: id, label: Id , widget: number}
      - { name: publishData, label: PublishData, widget: datetime }
      - { name: title, label: Title ,widget: string}
      - { name: team, label: Team ,widget: string}
      - { name: price, label: Price }
      - { name: salaryClass, label: SalaryClass ,widget: string}
      - { name: location, label: Location }
      - { name: locationArea, label: LocationArea ,widget: string}
      - { name: member, label: Member ,widget: string}
      - { name: experience, label: Experience,widget: string }
      - { name: aboutCompany, label: AboutCompany,widget: string }
      - { name: admin, label: Admin }
      - { name: tittleImg, label: TittleImg ,widget: image}
      - { name: logo, label: Logo ,widget: image}
      - { name: body, label: Body, widget: markdown }


  - name: freelancersInfo
    label: Freelancers Info
    folder: src/freelancersInfo
    create: true
    fields:
      - { name: id, label: Id , widget: number}
      - { name: name, label: Name ,widget: string}
      - { name: profession, label: Profession ,widget: string}
      - { name: rating, label: Rating ,widget: number}
      - { name: location, label: Location , widget: string}
      - { name: member, label: Member ,widget: string}
      - { name: rate, label: Rate,widget: string }
      - { name: lastReview, label: Last Review,widget: string }
      - { name: onlineStatus, label: Online Status , widget: boolean }
      - { name: profile, label: Profile ,widget: image}

  - name: whyChooseUs
    label: Why Choose Us
    folder: src/whyChooseUs
    create: true
    fields:
      - { name: id, label: Id , widget: number}
      - { name: sectionTitle, label: Section Title ,widget: string}
      - { name: sectionSubTitle, label: Section SubTitle ,widget: string}
      - { name: sectionCards, label: sectionCards ,widget: object}

  - name: logoSection
    label: Clint Logo Section
    folder: src/pageMd
    file: src/pageMd/logoSection.md
    create: true
    fields:
      - { name: id, label: Id , widget: number}
      - { name: image1, label: Logo 1 ,widget: image}
      - { name: image2, label: Logo 2 ,widget: image}
      - { name: image3, label: Logo 3 ,widget: image}
      - { name: image4, label: Logo 4 ,widget: image}
      - { name: image5, label: Logo 5 ,widget: image}

  - name: index
    label: Home
    folder: src/pageMd
    file: src/pageMd/index.md
    create: true
    fields:
      - { name: id, label: Id , widget: number}

      - name: logoSection
       label: Logo Section 
       widget: list
        fields:
            - { name: logo1, label: Logo 1 ,widget: image}
            - { name: logo2, label: Logo 2 ,widget: image}
            - { name: logo3, label: Logo 3 ,widget: image}
            - { name: logo4, label: Logo 4 ,widget: image}
            - { name: logo5, label: Logo 5 ,widget: image}