backend:
  name: git-gateway
  repo: dvsrshohan/gatsby
  branch: main
  
media_folder: static/img
public_folder: /img

collections:
  - name: jobs
    label: Jobs
    folder: src/jobs
    create: true
    fields:
      - { name: id, label: Id , widget: number}
      - { name: publishData, label: PublishData, widget: datetime }
      - { name: title, label: Title ,widget: string}
      - { name: team, label: Team ,widget: string}
      - { name: price, label: Price }
      - { name: salaryClass, label: SalaryClass ,widget: string}
      - { name: location, label: Location }
      - { name: locationArea, label: LocationArea ,widget: string}
      - { name: member, label: Member ,widget: string}
      - { name: experience, label: Experience,widget: string }
      - { name: aboutCompany, label: AboutCompany,widget: string }
      - { name: admin, label: Admin }
      - { name: tittleImg, label: TittleImg ,widget: image}
      - { name: logo, label: Logo ,widget: image}
      - { name: body, label: Body, widget: markdown }


  - name: freelancersInfo
    label: Freelancers Info
    folder: src/freelancersInfo
    create: true
    fields:
      - { name: id, label: Id , widget: number}
      - { name: name, label: Name ,widget: string}
      - { name: profession, label: Profession ,widget: string}
      - { name: rating, label: Rating ,widget: number}
      - { name: location, label: Location , widget: string}
      - { name: member, label: Member ,widget: string}
      - { name: rate, label: Rate,widget: string }
      - { name: lastReview, label: Last Review,widget: string }
      - { name: onlineStatus, label: Online Status , widget: boolean }
      - { name: profile, label: Profile ,widget: image}

  - name: whyChooseUs
    label: Why Choose Us
    folder: src/whyChooseUs
    create: true
    fields:
      - { name: id, label: Id , widget: number}
      - { name: sectionTitle, label: Section Title ,widget: string}
      - { name: sectionSubTitle, label: Section SubTitle ,widget: string}
      - name: sectionCards
        label: sectionCards 
        widget: list 
        fields: 
          - { name: title, label: Title ,widget: string}
          - { name: cardImages, label: Card Images ,widget: image}
          - { name: cardDetails, label: Card Details ,widget: string}

  - name: testimonial
    label: Testimonial
    folder: src/testimonial
    create: true
    fields:
      - { name: title, label: Section Title ,widget: string}
      - { name: subTitle, label: Section Sub Title ,widget: string}
      -  name: testimonial
         label: Testimonial  Items
         widget: list 
         fields: 
            - { name: name, label: Name ,widget: string}
            - { name: title, label: Title ,widget: string}
            - { name: image, label: Image ,widget: image}
            - { name: rating, label: Rating ,widget: Number}
            - { name: details, label: Details ,widget: string}

  - name: counter
    label: Counter
    folder: src/counter
    create: true
    fields:
      - { name: title, label: Section Title ,widget: string}
      -  name: counterData
         label: Counter Data
         widget: list 
         fields: 
            - { name: number, label: Counter Number ,widget: Number}
            - { name: title, label: Counter Title ,widget: string}

  - name: pricingPlan
    label: Pricing Plan
    folder: src/pricingPlan
    create: true
    fields:
      - { name: section, label: Section Title ,widget: string}
      - { name: subTitle, label: Section Sub Title ,widget: string}
      -  name: pricingPlan
         label: Pricing Plan
         widget: list 
         fields: 
            - { name: title, label: Title ,widget: string}
            - { name: price, label: Price ,widget: number}
            - { name: duration, label: Duration ,widget: string}
            - name: pricingPlanItems
              label: pricingPlanItems
              widget: list 
              fields: 
                  - { name: items, label: Title ,widget: string}

  - name: logoSection
    label: Clint Logo Section
    folder: src/logoSection
    create: true
    fields:
      - { name: section, label: Section Title ,widget: string}
      -  name: Logos
         label: Clint Logos
         widget: list 
         fields: 
            - { name: logo, label: Logo ,widget: image}

  - name: howItWorks
    label: How It Works
    folder: src/howItWorks
    create: true
    fields:
      - { name: section, label: Title ,widget: string}
      - { name: title, label: Section Title ,widget: string}
      - { name: sectionImage, label: Section Image ,widget: image}
      -  name: faq
         label: FAQ
         widget: list 
         fields: 
            - { name: question, label: Question ,widget: string}
            - { name: id, label: id ,widget: number}
            - { name: idColor, label: Id Color ,widget: string}
            - { name: idBGColor, label: Id Background Color ,widget: string}
            - { name: answer, label: answer ,widget: string}

  - name: hero
    label: Hero
    folder: src/hero
    create: true
    fields:
      - { name: section, label: Title ,widget: string}
      -  name: sliderItems
         label: Slider Items
         widget: list 
         fields: 
            - { name: heroTitleFirst, label: heroTitleFirst ,widget: string}
            - { name: heroTitleSecond, label: heroTitleSecond ,widget: string}
            - { name: heroTitleThird, label: heroTitleThird ,widget: string}
            - { name: heroSubTitle, label: Hero Sub Title ,widget: string}
            - { name: heroImage, label: Hero Image ,widget: image}
            - { name: id, label: id ,widget: number}
            - { name: heroUserImage, label: Hero Card User Image ,widget: image}
            - { name: heroUserName, label: Hero Card User Name ,widget: string}
            - { name: heroUserTitle, label: Hero Card User Title ,widget: string}

  - name: latestBlog
    label: Latest Blog
    folder: src/latestBlog
    create: true
    fields:
      - { name: id, label: id ,widget: number}
      - { name: section, label: Title ,widget: string}
      - { name: subTitle, label: Sub Title ,widget: string}
      -  name: news
         label: News
         widget: list 
         fields: 
            - { name: id, label: id ,widget: number}
            - { name: image, label: Image ,widget: image}
            - { name: author, label: Author ,widget: string}
            - { name: date, label: Date ,widget: string}
            - { name: title, label: News Title ,widget: string}
            - { name: details, label: Details ,widget: string}
            - { name: image2, label: Image Tow,widget: image}
            - { name: author2, label: Author Two,widget: string}
            - { name: date2, label: Date Two,widget: string}
            - { name: title2, label: News Title Two,widget: string}
            - { name: details2, label: Details Two,widget: string}
