export const featureProfile = [
  {
    id: 1,
    image: "/images/placeholder1.png",
    username: "David Hutapea",
    prof: "UI/UX developer",
    rating: 4.3,
    price: 84,
  },
  {
    id: 2,
    image: "/images/placeholder2.png",
    username: "Henry Simatupang",
    prof: "Photographer",
    rating: 4.8,
    price: 95,
  },
  {
    id: 3,
    image: "/images/placeholder3.png",
    username: "Jennie Smith",
    prof: "Content writer",
    rating: 4.6,
    price: 88,
  },
  {
    id: 4,
    image: "/images/placeholder4.png",
    username: "Louis Anderson",
    prof: "Customer support",
    rating: 4.3,
    price: 27,
  },
  {
    id: 5,
    image: "/images/placeholder1.png",
    username: "Thomas Holden",
    prof: "Customer support",
    rating: 4.3,
    price: 27,
  },
  {
    id: 6,
    image: "/images/placeholder2.png",
    username: "Shirley Beauchamp",
    prof: "Customer support",
    rating: 4.3,
    price: 27,
  },
  {
    id: 7,
    image: "/images/placeholder3.png",
    username: "Travis Bennett",
    prof: "Customer support",
    rating: 4.3,
    price: 27,
  },
];

export const featuredJobs = [
  {
    id: 1,
    image: "/images/companyLogo1.png",
    programmer: "Database Programmer",
    title: "Maximoz Team",
    price: "$14,000 - $25,000",
    location: "London, England",
  },

  {
    id: 2,
    image: "/images/companyLogo2.png",
    programmer: "UI/UX Designer",
    title: "Colo Colo Studios",
    price: "$17,000 - $75,000",
    location: "Dhaka, Bangladesh",
  },

  {
    id: 3,
    image: "/images/companyLogo3.png",
    programmer: "Content Writer",
    title: "Faster WOY Crew",
    price: "$12,000 - $31,000",
    location: "Australia, Canada",
  },

  {
    id: 4,
    image: "/images/companyLogo4.png",
    programmer: "Application developer",
    title: "B Technologies",
    price: "$21,000 - $95,000",
    location: "Dinajpur, Rongpur",
  },
];
export const jobs = [
  {
    id: 1,
    image: "/images/jobLogo1.png",
    programmer: "Senior UX Designer",
    title: "Highspeed Studios",
    price: "$14,000 - $25,000",
    location: "London, England",
  },

  {
    id: 2,
    image: "/images/jobLogo2.png",
    programmer: "Junior UX Designer",
    title: "Vvibu Leu Boz Studios",
    price: "$8,000 - $12,000",
    location: "Australia, Canada",
  },

  {
    id: 3,
    image: "/images/jobLogo3.png",
    programmer: "Principal UX Designer",
    title: "Lowvoltages Team",
    price: "$11,000 - $60,000",
    location: "London, England",
  },
  {
    id: 4,
    image: "/images/jobLogo4.png",
    programmer: "Senior UX Designer",
    title: "Lowvoltages Team",
    price: "$11,000 - $60,000",
    location: "London, England",
  },
  {
    id: 5,
    image: "/images/jobLogo5.png",
    programmer: "Principal UX Designer",
    title: "Lowvoltages Team",
    price: "$11,000 - $60,000",
    location: "London, England",
  },

  {
    id: 6,
    image: "/images/jobLogo6.png",
    programmer: "Junior UX Designer",
    title: "Vvibu Leu Boz Studios",
    price: "$8,000 - $12,000",
    location: "Australia, Canada",
  },

  {
    id: 7,
    image: "/images/jobLogo7.png",
    programmer: "Principal UX Designer",
    title: "Lowvoltages Team",
    price: "$11,000 - $60,000",
    location: "London, England",
  },
  {
    id: 8,
    image: "/images/jobLogo8.png",
    programmer: "Senior UX Designer",
    title: "Lowvoltages Team",
    price: "$11,000 - $60,000",
    location: "London, England",
  }
];

export const freelancersInfo = [
  {
    _id: "1",
    name: "Angela Moss",
    profession: "Content Writer",
    rating: "4.3",
    location: "New York, US",
    member: "Oct 2008",
    rate: "$50/hr",
    lastReview: "4 Days ago",
    onlineStatus: true,
    profile: "/images/freelancer.png",
  },

  {
    _id: "2",
    name: "Jimmy Lee",
    profession: "Programmer",
    rating: "4.7",
    location: "Jakarta, Indonesia",
    member: "Oct 2014",
    rate: "$26/hr",
    lastReview: "7 hours ago",
    onlineStatus: false,
    profile: "/images/freelancer2.png",
  },

  {
    _id: "3",
    name: "Melinda Humbles",
    profession: "Graphic Designer",
    rating: "4",
    location: "New York",
    member: "Oct 2020",
    rate: "$92/hr",
    lastReview: "1 hours ago",
    onlineStatus: true,
    profile: "/images/freelancer3.png",
  },

  {
    _id: "4",
    name: "Jordan Sigh",
    profession: "Content Writer",
    rating: "4.8",
    location: "New York",
    member: "Nov 2020",
    rate: "$38/hr",
    lastReview: "2 days ago",
    onlineStatus: true,
    profile: "/images/freelancer4.png",
  },

  {
    _id: "5",
    name: "Mahmud",
    profession: "Programmer",
    rating: "4.9",
    location: "Jakarta, Indonesia",
    member: "Nov 2014",
    rate: "$36/hr",
    lastReview: "3 days ago",
    onlineStatus: false,
    profile: "/images/freelancer5.png",
  },

  {
    _id: "6",
    name: "Roberto Karloz",
    profession: "Photographer",
    rating: "3",
    location: "England",
    member: "Feb 2018",
    rate: "$27/hr",
    lastReview: "5 days ago",
    onlineStatus: true,
    profile: "/images/freelancer6.png",
  },

  {
    _id: "7",
    name: "Gwen Claudya",
    profession: "Programmer",
    rating: "5",
    location: "Australia",
    member: "Mar 2017",
    rate: "$47/hr",
    lastReview: "7 days ago",
    onlineStatus: false,
    profile: "/images/freelancer7.png",
  },

  {
    _id: "8",
    name: "Bella Smith",
    profession: "Content Writer",
    rating: "4.7",
    location: "Pakistan",
    member: "Dec 2015",
    rate: "$84/hr",
    lastReview: "5 minutes ago",
    onlineStatus: true,
    profile: "/images/freelancer8.png",
  },

  {
    _id: "9",
    name: "Kokom ",
    profession: "Photographer",
    rating: "4",
    location: "India",
    member: "Dec 2019",
    rate: "$19/hr",
    lastReview: "47 minutes ago",
    onlineStatus: true,
    profile: "/images/freelancer9.png",
  },

  {
    _id: "10",
    name: "Fanny Fancyson ",
    profession: "Programmer",
    rating: "4",
    location: "Japan",
    member: "Jan 2023",
    rate: "$15/hr",
    lastReview: "10 minutes ago",
    onlineStatus: true,
    profile: "/images/freelancer10.png",
  },

  {
    _id: "11",
    name: "Louis Anderson",
    profession: "Content Writer",
    rating: "5",
    location: "USA",
    member: "Feb 2023",
    rate: "$23/hr",
    lastReview: "36 minutes ago",
    onlineStatus: true,
    profile: "/images/freelancer11.png",
  },

  {
    _id: "12",
    name: "Samantha William",
    profession: "Graphic designer",
    rating: "5",
    location: "Bangladesh",
    member: "Feb 2022",
    rate: "$26/hr",
    lastReview: "20 minutes ago",
    onlineStatus: true,
    profile: "/images/freelancer12.png",
  },
];

export const jobDetails = [
  {
    "_id": "1",
    "tittleImg": "./images/recentJobs/job1.png",
    "title": "Senior UX Designer",
    "team": "high speed studios",
    "price": "$14,000 - $25,000",
    "salaryClass": "Monthly Salary",
    "locationArea": "London, England",
    "location": "London",
    "apply": "Apply Now",
    "icon": "FaHeart",
    "locationIcon": "FaMapMarkerAlt",
    "experience": "2-3",
    "info": {
      "admin": "shohanur rahman",
      "publishData": "Nov 12th, 2020",
      "aboutCompany": "request a letter of application, it never hurts to include one. If they do ask you to send a letter, make sure to follow the directions exactly (for example, they might ask you to send the letter as an email attachment, or type it directly into their online application system).Use business letter format. Use a formal business letter format when writing your letter. Include your contact information at the top, the date, and the employer’s contact ",
      "rating": "4.8",
      "employ": "100-800"
    },
    "details": "Always write one. Unless a job posting specifically says not to send a letter of application or cover letter, you should always send one. Even if the company does not request a letter of application, it never hurts to include one. If they do ask you to send a letter, make sure to follow the directions exactly (for example, they might ask you to send the letter as an email attachment, or type it directly into their online application system).Use business letter format. Use a formal business letter format when writing your letter. Include your contact information at the top, the date, and the employer’s contact information. Be sure to provide a salutation at the beginning, and your signature at the end.Sell yourself. Throughout the letter, focus on how you would benefit the company. Provide specific examples of times when you demonstrated skills or abilities that would be useful for the job, especially those listed in the job posting or description. If possible, include examples of times when you added value to a company."
  },
  {
    "_id": "2",
    "tittleImg": "./images/recentJobs/job2.png",
    "title": "Intern UX Designer",
    "team": "Maximoz Team",
    "price": "$500 - $1,000",
    "salaryClass": "Monthly Salary",
    "locationArea": "Manchester, England",
    "location": "London",
    "apply": "Apply Now",
    "icon": "FaHeart",
    "locationIcon": "FaMapMarkerAlt",
    "experience": "1-3",
    "info": {
      "admin": "Alekgendara",
      "publishData": "Oct 15th, 2022",
      "aboutCompany": "abilities that are emphasized in the listing). Try to include some of those words in your cover letter. This will help the employer see that you are a strong fit for the job.Keep it brief. Keep your letter under a page long, with no more than about four paragraphs. An employer is more likely to read a concise letter. Proofread and edit. Employers are likely to overlook an application",
      "rating": "4.9",
      "employ": "100-200"
    },
    "details": "Use keywords. Reread the job listing, circling any keywords (such as skills or abilities that are emphasized in the listing). Try to include some of those words in your cover letter. This will help the employer see that you are a strong fit for the job.Keep it brief. Keep your letter under a page long, with no more than about four paragraphs. An employer is more likely to read a concise letter. Proofread and edit. Employers are likely to overlook an application with a lot of errors. Read through your cover letter, and if possible, ask a friend or career counselor to review the letter. Proofread for any grammar or spelling errors."
  },
  {
    "_id": "3",
    "tittleImg": "./images/recentJobs/job3.png",
    "title": "Vvibu Leu Boz Studios",
    "team": "Maximoz Team",
    "price": "$8,000 - $12,000",
    "salaryClass": "Monthly Salary",
    "locationArea": "Oxford, England",
    "location": "England",
    "apply": "Apply Now",
    "icon": "FaHeart",
    "locationIcon": "FaMapMarkerAlt",
    "experience": "6-1.5",
    "info": {
      "admin": "John doe",
      "publishData": "Mer 15th, 2023",
      "aboutCompany": " Veggies to Go customer and an experienced admin, I would love to help the company achieve its mission of making healthy produce as available as takeout.I’ve worked for small companies for my entire career, and I relish the opportunity to wear many hats and work with the team to succeed. In my latest role as an administrative assistant at Beauty Corp, I saved my employer thousands of dollars in temp workers by implementing a self-scheduling system for the customer service reps that cut down on canceled shifts. I also learned web desig",
      "rating": "5",
      "employ": "100-500"
    },
    "details": "I was so excited when my former coworker, Jay Lopez, told me about your opening for an administrative assistant in your Portland offices. A long-time Veggies to Go customer and an experienced admin, I would love to help the company achieve its mission of making healthy produce as available as takeout.I’ve worked for small companies for my entire career, and I relish the opportunity to wear many hats and work with the team to succeed. In my latest role as an administrative assistant at Beauty Corp, I saved my employer thousands of dollars in temp workers by implementing a self-scheduling system for the customer service reps that cut down on canceled shifts. I also learned web design, time sheet coding, and perfected my Excel skills. I’ve attached my resume for your consideration and hope to speak with you soon about your needs for the role."
  },
  {
    "_id": "4",
    "tittleImg": "./images/recentJobs/job4.png",
    "title": "Principal UX Designer",
    "team": "Lowvoltages Team",
    "price": "$11,000 - $60,000",
    "salaryClass": "Monthly Salary",
    "locationArea": "London, England",
    "location": "England",
    "apply": "Apply Now",
    "icon": "FaHeart",
    "locationIcon": "FaMapMarkerAlt",
    "experience": "1-4",
    "info": {
      "admin": "Elong mux",
      "publishData": "Feb 10th, 2023",
      "aboutCompany": "fund is money you have set aside to cover any financial emergencies or unexpected expenses that may come up. Those can include anything that you haven't planned for, such as unexpected car repairs, medical bills, unemployme",
      "rating": "4.3",
      "employ": "20-80"
    },
    "details": "An emergency fund is money you have set aside to cover any financial emergencies or unexpected expenses that may come up. Those can include anything that you haven't planned for, such as unexpected car repairs, medical bills, unemployment or other income loss, property damage, or family emergencies."
  },
  {
    "_id": "5",
    "tittleImg": "./images/recentJobs/job5.png",
    "title": "Senior web developer",
    "team": "B Technologies",
    "price": "$5,000 - $40,000",
    "salaryClass": "Monthly Salary",
    "locationArea": "Dinajpur, Bangladesh",
    "location": "Bangladesh",
    "apply": "Apply Now",
    "icon": "FaHeart",
    "locationIcon": "FaMapMarkerAlt",
    "experience": "4-8",
    "info": {
      "admin": "Abu hayat",
      "publishData": "Feb 10th, 2023",
      "aboutCompany": "job application letter is very different from a quick email to a friend or a thank-you note to a relative. Hiring managers and potential interviewers have certain expectations when it comes to the letter's presentation and appearance, from length (no more than a page) to font size and style to letter spacing: Length: A letter of application should be no more than one page long. Three to four paragraphs is typical.Format and Page Margins: A letter of application should be single-spaced with a space between each paragr",
      "rating": "4.6",
      "employ": "1-20"
    },
    "details": "Writing a job application letter is very different from a quick email to a friend or a thank-you note to a relative. Hiring managers and potential interviewers have certain expectations when it comes to the letter's presentation and appearance, from length (no more than a page) to font size and style to letter spacing: Length: A letter of application should be no more than one page long. Three to four paragraphs is typical.Format and Page Margins: A letter of application should be single-spaced with a space between each paragraph. Use about 1 margins and align your text to the left, which is the standard alignment for most documents. ont: Use a traditional font such as Times New Roman, Arial, or Calibri. The font size should be between 10 and 12 points."
  },
  {
    "_id": "6",
    "tittleImg": "./images/recentJobs/job7.png",
    "title": "Backend developer",
    "team": "Australia inc",
    "price": "$7,000 - $53,000",
    "salaryClass": "Monthly Salary",
    "locationArea": "Australia, USA",
    "location": "USA",
    "apply": "Apply Now",
    "icon": "FaHeart",
    "locationIcon": "FaMapMarkerAlt",
    "experience": "5-10",
    "info": {
      "admin": "Larry page",
      "publishData": "Feb 10th, 2023",
      "aboutCompany": "also set rules for the sections included in the letter, from salutation to sign-off, and how the letter is organized. Here's a quick lowdown on the main sections included in a job application letter:1 Heading: A letter of application should begin with both your and the employer's contact info",
      "rating": "4.9",
      "employ": "1-300"
    },
    "details": "There are also set rules for the sections included in the letter, from salutation to sign-off, and how the letter is organized. Here's a quick lowdown on the main sections included in a job application letter:1 Heading: A letter of application should begin with both your and the employer's contact information (name, address, phone number, email) followed by the date. If this is an email rather than an actual letter, include your contact information at the end of the letter, after your signature. Salutation: This is your polite greeting. The most common salutation is Dear Mr./Ms. followed by the person's last name. Find out more about appropriate cover letter salutations, including what to do if you don't know the person's name, or are unsure of a contact's gender. Body of the letter: Think of this section as being three distinct parts. In the first paragraph, you'll want to mention the job you are applying for and where you saw the job listing. The next paragraph(s) are the most important part of your letter. Remember how you gathered all that information about what employers were seeking, and how you could meet their needs? This is where you'll share those relevant details on your experience and accomplishments.  The third and last part of the body of the letter will be your thank you to the employer; you can also offer follow-up information. Complimentary Close: Sign off your email with a polite close, such as Best or Sincerely, followed by your name."
  },
  {
    "_id": "7",
    "tittleImg": "./images/recentJobs/job8.png",
    "title": "Senior Software developer",
    "team": "USA tech LLC",
    "price": "$20,000 - $99,000",
    "salaryClass": "Monthly Salary",
    "locationArea": "Califonia, USA",
    "location": "USA",
    "apply": "Apply Now",
    "icon": "FaHeart",
    "locationIcon": "FaMapMarkerAlt",
    "experience": "5-15",
    "info": {
      "admin": "Lazzer",
      "publishData": "Feb 11th, 2020",
      "aboutCompany": "Always write one. Unless a job posting specifically says not to send a letter of application or cover letter, you should always send one. Even if the company does not request a letter of application, it never hurts to include one. If they do ask you to send a letter, make sure to follow the directions exactly (for example, they might ask you to send the letter as an email attachment.",
      "rating": "4.9",
      "employ": "1-300"
    },
    "details": "Always write one. Unless a job posting specifically says not to send a letter of application or cover letter, you should always send one. Even if the company does not request a letter of application, it never hurts to include one. If they do ask you to send a letter, make sure to follow the directions exactly (for example, they might ask you to send the letter as an email attachment, or type it directly into their online application system). Use business letter format. Use a formal business letter format when writing your letter. Include your contact information at the top, the date, and the employer’s contact information. Be sure to provide a salutation at the beginning, and your signature at the end. Sell yourself. Throughout the letter, focus on how you would benefit the company. Provide specific examples of times when you demonstrated skills or abilities that would be useful for the job, especially those listed in the job posting or description. If possible, include examples of times when you added value to a company."
  },
  {
    "_id": "8",
    "tittleImg": "./images/recentJobs/job9.png",
    "title": "React developer",
    "team": "CGI LLC",
    "price": "$2,000 - $15,000",
    "salaryClass": "Monthly Salary",
    "locationArea": "Califonia, USA",
    "location": "USA",
    "apply": "Apply Now",
    "icon": "FaHeart",
    "locationIcon": "FaMapMarkerAlt",
    "experience": "1-2",
    "info": {
      "admin": "Lazzer",
      "publishData": "Feb 11th, 2020",
      "aboutCompany": "Always write one. Unless a job posting specifically says not to send a letter of application or cover letter, you should always send one. Even if the company does not request a letter of application, it never hurts to include one. If they do ask you to send a letter, make sure to follow the directions exactly (for example, they might ask you to send the letter as an email attachment.",
      "rating": "4.9",
      "employ": "1-300"
    },
    "details": "Use keywords. Reread the job listing, circling any keywords (such as skills or abilities that are emphasized in the listing). Try to include some of those words in your cover letter. This will help the employer see that you are a strong fit for the job.Keep it brief. Keep your letter under a page long, with no more than about four paragraphs. An employer is more likely to read a concise letter.Proofread and edit. Employers are likely to overlook an application with a lot of errors. Read through your cover letter, and if possible, ask a friend or career counselor to review the letter. Proofread for any grammar or spelling errors."
  }
]